# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Allan
tagline:          'Data Science, Apache Pig, Hadoop, Blogging, Tweets, Astrophysics'
url:              http://allanl.com
shorturl:         allanl.com

author:
  name:           'Allan'
  url:            https://twitter.com/YupingLu

paginate:         1